### ISSUE TITLE
Make _useKResponsiveElement composable public and Remove KResponsiveElementMixin

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri-design-system#711] opened 2024-08-01 20:21 UTC
## Product
KDS, Kolibri (Studio and KDP doesnt seem to be using the KResponsiveElementMixin).

## Description

Transition the internal composable [_useKResponsiveElement](https://github.com/learningequality/kolibri-design-system/blob/6a6865f1060e1da160b77b7b851f82f340f453a1/lib/composables/_useKResponsiveElement.js) to a public-facing composable named `useKResponsiveElement`. Then, remove the [KResponsiveElementMixin](https://github.com/learningequality/kolibri-design-system/blob/6a6865f1060e1da160b77b7b851f82f340f453a1/lib/KResponsiveElementMixin.js) mixin from the codebase. This involves the following steps:

* Rename `_useKResponsiveElement.js` file to `useKResponsiveElement.js`.
* Update all internal references to use the new file name.
* Migrate all internal references of `KResponsiveElementMixin` to use the new `useKResponsiveElement` composable.
* Remove the `KResponsiveElementMixin.js` file.
* Create a new documentation page for `useKResponsiveElement`. 
* Remove the old documentation page of `KResponsiveElementMixin`.

## The Value Add
After this, we will able to replace all KResponsiveElement mixins with this composable. This aligns with our plan of adopting composables over mixins.

**Comment by lokesh-sagi125** [comment] 2024-08-20 06:48
hi, @AlexVelezLl  can you assign this issue to me?

**Comment by MisRob** [comment] 2024-08-20 09:00
Hey @lokesh-sagi125, I think the issue is suitable for contribution, however @AlexVelezLl assigned himself some time ago so I'm not sure if there's some work in progress. Let's hear from Alex first where things are.

**Comment by AlexVelezLl** [comment] 2024-08-20 13:18
Hey @lokesh-sagi125! This issue is already assigned to me, and I have already made some progress :sweat_smile:. But you can always check our list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all our repositories :open_hands:.

**Closed as completed** 2024-09-30 22:01 UTC
Labels: type: task, P2 - normal, TAG: dev experience, Component: KResponsiveElementMixin, help wanted
