### ISSUE TITLE
Kolibri Data Portal custom sorting option: The KSelect component for the custom date range does not support clicking a different date range after an initial selection

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri-design-system#343] opened 2022-06-28 18:59 UTC
## Product
Kolibri Data Portal

## Behavior
When you select a custom range to filter the data by, you can't easily select a different custom range. I would expect to click "Custom" again and have the modal pop up, but it does not:

![2022-06-27 12 06 41](https://user-images.githubusercontent.com/22602993/176261417-da8c65fa-693e-4312-ad4f-e54ed557aca9.gif)

## Steps to reproduce the issue
Open KDP, click on 'Data' and then 'Channels' and sort by Custom range. Then attempt to click Custom _again_ to sort by a different range, the button no longer does anything.

## Additional information
Notes from @jredrejo: "that's a problem of the KSelect component we have in our library. That component does not notify any event if the selection does not change. There's no solution with the current version of kolibri unless I do a fork of a part of its code what is generally a bad idea from a maintenance point of view."

**Comment by jredrejo** [comment] 2022-06-28 19:06
Duplicate of #342

**Closed by jredrejo** 2022-06-28 19:06 UTC
