### ISSUE TITLE
Update Docs for z-index & drop-shadow for better clarity

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri-design-system#813] opened 2024-10-29 23:34 UTC
🌱 **Are you new to the codebase? Welcome! Please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).**

## Desired behavior

In discussion re:  https://github.com/learningequality/kolibri/pull/12630 we discussed that the [(pr 723 Netlify Deploy version) Elevation & Shadow docs](https://deploy-preview-723--kolibri-design-system.netlify.app/styling/#elevation) is a bit ambiguous and could use a bit of reworking. ([Related Notion doc](https://www.notion.so/learningequality/2024-10-29-KDS-Tactical-120f45d6ef9680ba87a5f1acee5f3d44?p=12ef45d6ef9680a7a59bda4d51634ce5&pm=s)).

This follows up from #723 which added docs for drop-shadows

- The Google Material Design elevation image is not relevant to our approach to drop-shadows, so it should be moved down to the "z-index" section where it is more relevant.

### Acceptance criteria
- [ ] The dropshadow image is displayed under the z-index section. 

## (Optional) The Value Add

Clearer guidance reduces the potential for confusion while referring to the drop-shadow docs.

**Comment by RONAK-AI647** [comment] 2024-11-08 15:24
Hey @AlexVelezLl Assign it to me please!!!

**Comment by AlexVelezLl** [comment] 2024-11-08 15:25
For sure @RONAK-AI647! Thanks for volunteering!

**Comment by RONAK-AI647** [comment] 2024-11-08 15:43
Hey @AlexVelezLl ,it is mentioned 'Google Material Design elevation image is not relevant to our approach to drop-shadows'
I suppose the image under "elevation and shadows" is more relevant .

**Comment by AlexVelezLl** [comment] 2024-11-08 16:33
Hey @RONAK-AI647! Yes, its the same image, but it should be shown in the Z-index section where is more relevant

**Comment by RONAK-AI647** [comment] 2024-11-08 16:46
@AlexVelezLl ,I am bit confused ,few minutes earlier the pic was this                                                                                                                
![Image](https://github.com/user-attachments/assets/1afb2f71-4ec9-4291-8e20-9f254b20d0a1)

and now it shows this


![Image](https://github.com/user-attachments/assets/68f99f83-2065-4414-8999-09c9b24a0120)

Another thing ,if I just move it to z-index, the dropshadows section would look empty ,as the pic is showcased in an example with a logic code.

**Comment by AlexVelezLl** [comment] 2024-11-08 16:50
Oh I think you are checking the wrong website 😅. In the issue is described this docs page: https://deploy-preview-723--kolibri-design-system.netlify.app/styling/#elevation which is from our develop branch. There you will find this image which is the one the issue talks about:

![Image](https://github.com/user-attachments/assets/ebfbc202-0d14-4529-9a10-98ee62d73e44)

**Comment by RONAK-AI647** [comment] 2024-11-08 17:20
I was doing the same thing ,but due to misconception ,I stepped back....anyways thankyou @AlexVelezLl I have raised the PR.

**Comment by MisRob** [comment] 2024-12-02 19:02
Closed by https://github.com/learningequality/kolibri-design-system/pull/819

**Closed as completed by MisRob** 2024-12-02 19:02 UTC
Labels: category: docs content, good first issue, help wanted
