### ISSUE TITLE
In KBreadcrumbs, give any truncated (e.g. "super long it...") items a title attr so it is readable when truncated

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri-design-system#208] opened 2021-03-25 18:36 UTC
## Desired behavior

Implement something similar to https://github.com/learningequality/kolibri/pull/7915

But for items in KBreadcrumbs

## Current behavior

In this example, the long item at the end is truncated, and there is no way to read the whole text

![image](https://user-images.githubusercontent.com/10248067/112525474-290b9800-8d5e-11eb-9d86-8437ea780256.png)

**Comment by RONAK-AI647** [comment] 2024-11-14 18:26
@MisRob @AlexVelezLl may i try this issue once , let you know the results soon.

**Comment by MisRob** [comment] 2024-11-15 09:24
Yes sure @RONAK-AI647. Is the expected behavior clear?

**Comment by RONAK-AI647** [comment] 2024-11-19 14:48
@MisRob I will be thankful if you summarize the expected behavior.

**Comment by MisRob** [comment] 2024-11-20 07:09
@RONAK-AI647 The issue this is trying to resolve is that when there is an item with truncated text in `KBreadcrumbs`, users have no way to read the whole text of that breadcrumb. The proposed solution is to use [the title attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) for such an item.

However, compared to similar work in https://github.com/learningequality/kolibri/pull/7915, in `KBreadcrumbs`, I don't see a way to detect whether an item is truncated or no since we use CSS to achieve that.

So I wonder if we could apply the `title` to all breadcrumb items, even those that are not truncated. @radinamatic do you have any recommendations on how to best approach this?

**Comment by RONAK-AI647** [comment] 2024-11-21 17:01
@MisRob ,take a look whenever free at the PR i raised and let me know if something else's required. If @radinamatic recommends any change or new approach , will work on that as well. Thank You.

**Comment by MisRob** [comment] 2024-11-22 18:31
Thank you @RONAK-AI647. Just responded in the PR.

**Comment by MisRob** [comment] 2024-12-17 17:54
Closed by https://github.com/learningequality/kolibri-design-system/pull/872

**Closed by MisRob** 2024-12-17 17:54 UTC
Labels: category: library, type: task, P1 - important, TODO: needs decisions, Component: KBreadcrumbs, good first issue, help wanted
