### ISSUE TITLE
KIconButton has redundant props

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#175] opened 2021-02-23 17:41 UTC
## Expected behavior

The tooltip and aria label should always be the same for a `KIconButton`

## Actual behavior

There are separate props and aria label is not required:

```js
      ariaLabel: {
        type: String,
        default: null,
      },
      tooltip: {
        type: String,
        required: true,
      },
```

**Comment by marcellamaki** [comment] 2021-09-07 13:51
Closing as duplicate of #168

**Closed by marcellamaki** 2021-09-07 13:51 UTC
Labels: type: proposal, category: library

**Comment by indirectlylit** [comment] 2021-09-07 13:55
hah, and I filed those within a few days of each other 🤦
